name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write    

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      
      - name: Build binaries
        run: |
          bun install
          bun run build:mac
          bun run build:linux
          chmod +x dist/work-*
          cd dist
          tar -czf ../work-macos.tar.gz work-macos
          tar -czf ../work-linux.tar.gz work-linux
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            work-linux.tar.gz
            work-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}